version: '3.8'

services:
  paw-proxy:
    container_name: paw-proxy
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
      - "443:443"

  cache:
    container_name: paw-cache
    image: redis:6

  paw-frontend:
    container_name: paw-frontend
    image: node:16-alpine
    working_dir: /app
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "9000:9000"
    command: 
      ["ash", "-c", "npm install && npm run dev"]

  paw-directus:
    container_name: paw-directus
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extension
    depends_on:
      - paw-postgres
    env_file:
      - ./.env
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
       
      DATABASE_CLIENT: pg
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

      DATABASE_USER: ${DIRECTUS_DATABASE_USER}
      DATABASE_PASSWORD: ${DIRECTUS_DATABASE_PASSWORD}
      DATABASE_DATABASE: ${DIRECTUS_DATABASE_DATABASE}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      # PUBLIC_URL: "https://directus.example.com"

  paw-postgres:
    container_name: paw-postgres
    image: postgis/postgis:13-master
    volumes:
      - pgdata:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
volumes:
  pgdata:
