// Generated by https://quicktype.io

export interface Publication {
  id:           string;
  date_created: string;
  title:        string;
  content:      string;
  autor:        string;
  image:        null | string;
  likes:        string[] | null;
}
